# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T03:47:48+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Side(Enum):
    field_1 = 1
    field_2 = 2


class OrderStatus(Enum):
    field_1 = '-1'
    field_0 = '0'
    field_1_1 = '1'
    field_2 = '2'
    field_3 = '3'
    field_4 = '4'
    field_5 = '5'
    field_6 = '6'
    field_7 = '7'
    field_8 = '8'
    field_9 = '9'
    A = 'A'
    B = 'B'
    C = 'C'
    D = 'D'
    E = 'E'


class OrderType(Enum):
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_4 = 4


class TimeInForce(Enum):
    number_0 = 0
    number_1 = 1
    number_2 = 2
    number_3 = 3
    number_7 = 7


class AccountsGetResponse(BaseModel):
    accounts: Optional[List[str]] = Field(None, description='Unique account id')


class Side1(Enum):
    number_1 = 1
    number_2 = 2


class AccountsAccountOrderImpactPostRequest(BaseModel):
    Aux_Price: Optional[float] = Field(
        None,
        alias='Aux Price',
        description='Required price to support Stop and Stop Limit orders',
    )
    ContractId: Optional[float] = Field(
        None,
        description='The internal IB identifier for the trading product specified as an integer (can be obtained in response to /secdef request)',
    )
    Currency: Optional[str] = Field(
        None,
        description='The currency in which the FX pair trades (only for InstrumentType=CASH)',
    )
    CustomerOrderId: Optional[str] = Field(
        None, description='The order ID assigned by the customer.'
    )
    InstrumentType: Optional[str] = Field(
        None, description='The instrument type of the contract'
    )
    ListingExchange: Optional[str] = Field(
        None,
        description='The exchange on which the trading product is listed (only for InstrumentType=STK)',
    )
    Order_Type: Optional[OrderType] = Field(None, alias='Order Type')
    Price: Optional[float] = Field(None, description='The order price')
    Quantity: Optional[float] = Field(
        None, description='The number of units in the order; contracts or shares'
    )
    Side: Optional[Side1] = Field(None, description="Buy = '1', Sell = '2'")
    Ticker: Optional[str] = Field(
        None, description='The symbol that identifies the trading product'
    )
    Time_in_Force: Optional[TimeInForce] = Field(None, alias='Time in Force')


class AccountsAccountOrderImpactPostResponse(BaseModel):
    Commission: Optional[float] = None
    CommissionsCurrency: Optional[str] = None
    EquityWithLoan: Optional[float] = None
    InitMargin: Optional[float] = None
    InitMarginBefore: Optional[float] = None
    MaintMargin: Optional[float] = None
    MaintMarginBefore: Optional[float] = None
    MarginCurrency: Optional[str] = None
    MaxCommissions: Optional[float] = None
    MinCommissions: Optional[float] = None


class AccountsAccountOrdersPostRequest(BaseModel):
    Aux_Price: Optional[float] = Field(
        None,
        alias='Aux Price',
        description='Required Price to support Stop and Stop Limit orders',
    )
    ContractId: Optional[float] = Field(
        None,
        description='The internal IB identifier for the trading product specified as an integer (can be obtained in response to /secdef request)',
    )
    Currency: Optional[str] = Field(
        None,
        description='The currency in which the FX pair trades (only for InstrumentType=CASH)',
    )
    CustomerOrderId: Optional[str] = Field(
        None, description='The order ID assigned by the customer.'
    )
    GermanHftAlgo: Optional[bool] = Field(
        None,
        description='By setting this bool to false the customer attests that the order is not subject to German HFT Act, was not generated using any automated algorithm, and no algorithm determined or changed financial instrument, side, quantity, order type, limit or other price, trading venue or timing of this order. Currently we cannot accept orders where this flag is set to true. Such orders will be rejected.',
    )
    InstrumentType: Optional[str] = Field(
        None, description='The instrument type of the contract'
    )
    ListingExchange: Optional[str] = Field(
        None,
        description='The exchange on which the trading product is listed (only for InstrumentType=STK)',
    )
    Mifid2Algo: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II short code for algos that are responsible for investment decisions",
    )
    Mifid2DecisionMaker: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II short code for decision makers.",
    )
    Mifid2ExecutionAlgo: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II short code for algos that are responsible for handling/routing of the order.",
    )
    Mifid2ExecutionTrader: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II person responsible for handling/routing of the order",
    )
    Order_Type: Optional[OrderType] = Field(None, alias='Order Type')
    OrderRestrictions: Optional[float] = Field(
        None,
        description="MultiValueString representing the restrictions associated with\nan order. If more than one restriction is applicable to an\norder, this field can contain multiple instructions separated\nby space. \n'1' Program Trade\n'2' Index Arbitrage \n'3' Non-Index Arbitrage\n",
    )
    Outside_RTH: Optional[float] = Field(
        None,
        alias='Outside RTH',
        description='Indicates if order is active outside regular trading hours, where defined. 0 = no (default), 1 = yes',
    )
    Price: Optional[float] = Field(None, description='The order price')
    Quantity: Optional[float] = Field(
        None, description='The number of units in the order; contracts or shares'
    )
    Side: Optional[Side1] = Field(None, description="Buy = '1', Sell = '2'")
    Ticker: Optional[str] = Field(
        None, description='The symbol that identifies the trading product'
    )
    Time_in_Force: Optional[TimeInForce] = Field(None, alias='Time in Force')


class AccountsAccountOrdersCustomerOrderIdDeleteResponseItem(BaseModel):
    CustomerOrderId: Optional[str] = None
    OrderQty: Optional[float] = None
    OrderType_1: Optional[OrderType] = Field(None, alias='OrderType')
    Price: Optional[str] = None
    Side: Optional[Side1] = None
    Status: Optional[OrderStatus] = None
    Symbol: Optional[float] = None
    Warning: Optional[str] = None


class AccountsAccountOrdersCustomerOrderIdDeleteResponse(
    RootModel[List[AccountsAccountOrdersCustomerOrderIdDeleteResponseItem]]
):
    root: List[AccountsAccountOrdersCustomerOrderIdDeleteResponseItem]


class AccountsAccountOrdersCustomerOrderIdPutRequest(BaseModel):
    Aux_Price: Optional[float] = Field(
        None,
        alias='Aux Price',
        description='Required Price to support Stop and Stop Limit orders',
    )
    CustomerOrderId: Optional[str] = Field(
        None,
        description='The new order ID assigned by the customer for the modification.',
    )
    GermanHftAlgo: Optional[bool] = Field(
        None,
        description='By setting this bool to false the customer attests that the order is not subject to German HFT Act, was not generated using any automated algorithm, and no algorithm determined or changed financial instrument, side, quantity, order type, limit or other price, trading venue or timing of this order. Currently we cannot accept orders where this flag is set to true. Such orders will be rejected.',
    )
    Mifid2Algo: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II short code for algos that are responsible for investment decisions",
    )
    Mifid2DecisionMaker: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II short code for decision makers.",
    )
    Mifid2ExecutionAlgo: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II short code for algos that are responsible for handling/routing of the order.",
    )
    Mifid2ExecutionTrader: Optional[str] = Field(
        None,
        description="This field permits specification of the user's preregistered (via account management) MiFID II person responsible for handling/routing of the order",
    )
    Order_Type: Optional[OrderType] = Field(None, alias='Order Type')
    OrigCustomerOrderId: Optional[str] = Field(
        None, description='The order ID assigned by the customer'
    )
    Outside_RTH: Optional[float] = Field(
        None,
        alias='Outside RTH',
        description='Indicates if order is active outside regular trading hours, where defined. 0 = no (default), 1 = yes',
    )
    Price: Optional[float] = Field(None, description='The order price')
    Quantity: Optional[float] = Field(
        None, description='The number of units in the order; contracts or shares'
    )
    Side: Optional[Side1] = Field(None, description="Buy = '1', Sell = '2'")
    Time_in_Force: Optional[TimeInForce] = Field(None, alias='Time in Force')


class AccountsAccountOrdersCustomerOrderIdPutResponseItem(BaseModel):
    CustomerOrderId: Optional[str] = None
    OrderQty: Optional[float] = None
    OrderType_1: Optional[OrderType] = Field(None, alias='OrderType')
    Price: Optional[str] = None
    Side: Optional[Side1] = None
    Status: Optional[OrderStatus] = None
    Symbol: Optional[float] = None
    Warning: Optional[str] = None


class AccountsAccountOrdersCustomerOrderIdPutResponse(
    RootModel[List[AccountsAccountOrdersCustomerOrderIdPutResponseItem]]
):
    root: List[AccountsAccountOrdersCustomerOrderIdPutResponseItem]


class AccountsAccountPositionsGetResponseItem(BaseModel):
    AverageCost: Optional[float] = None
    ContractId: Optional[float] = None
    Position: Optional[float] = None


class AccountsAccountPositionsGetResponse(
    RootModel[List[AccountsAccountPositionsGetResponseItem]]
):
    root: List[AccountsAccountPositionsGetResponseItem]


class Info(BaseModel):
    AccountCode: Optional[str] = None
    AccountReady: Optional[str] = None
    AccountType: Optional[str] = None
    Cushion: Optional[str] = None
    DayTradesRemaining: Optional[str] = None
    DayTradesRemainingT: Optional[str] = None
    DayTradesRemainingT_2: Optional[str] = Field(None, alias='DayTradesRemainingT+2')
    DayTradesRemainingT_3: Optional[str] = Field(None, alias='DayTradesRemainingT+3')
    DayTradesRemainingT_4: Optional[str] = Field(None, alias='DayTradesRemainingT+4')
    HighestSeverity: Optional[str] = None
    Leverage_S: Optional[str] = Field(None, alias='Leverage-S')
    LookAheadNextChange: Optional[str] = None
    SegmentTitle_C: Optional[str] = Field(None, alias='SegmentTitle-C')
    SegmentTitle_S: Optional[str] = Field(None, alias='SegmentTitle-S')
    TradingType_S: Optional[str] = Field(None, alias='TradingType-S')
    WhatIfPMEnabled: Optional[str] = None


class LedgerItem(BaseModel):
    CashBalance: Optional[float] = None
    CashBalanceFXSegment: Optional[float] = None
    CashCumQty: Optional[float] = None
    ExchangeRate: Optional[float] = None
    FutureOptionMarketValue: Optional[float] = None
    FuturePNL: Optional[float] = None
    NetDividend: Optional[float] = None
    NetInterest: Optional[float] = None
    NetLiquidation: Optional[float] = None
    OptionMarketValue: Optional[float] = None
    RealizedPNL: Optional[float] = None
    StockMarketValue: Optional[float] = None
    TotalCashBalance: Optional[float] = None
    UnrealizedPNL: Optional[float] = None


class Summary(BaseModel):
    AccruedCash: Optional[float] = None
    AccruedCash_C: Optional[float] = Field(None, alias='AccruedCash-C')
    AccruedCash_S: Optional[float] = Field(None, alias='AccruedCash-S')
    AccruedDividend: Optional[float] = None
    AccruedDividend_C: Optional[float] = Field(None, alias='AccruedDividend-C')
    AccruedDividend_S: Optional[float] = Field(None, alias='AccruedDividend-S')
    AvailableFunds: Optional[float] = None
    AvailableFunds_C: Optional[float] = Field(None, alias='AvailableFunds-C')
    AvailableFunds_S: Optional[float] = Field(None, alias='AvailableFunds-S')
    Billable: Optional[float] = None
    Billable_C: Optional[float] = Field(None, alias='Billable-C')
    Billable_S: Optional[float] = Field(None, alias='Billable-S')
    BuyingPower: Optional[float] = None
    EquityWithLoanValue: Optional[float] = None
    EquityWithLoanValue_C: Optional[float] = Field(None, alias='EquityWithLoanValue-C')
    EquityWithLoanValue_S: Optional[float] = Field(None, alias='EquityWithLoanValue-S')
    ExcessLiquidity: Optional[float] = None
    ExcessLiquidity_C: Optional[float] = Field(None, alias='ExcessLiquidity-C')
    ExcessLiquidity_S: Optional[float] = Field(None, alias='ExcessLiquidity-S')
    FullAvailableFunds: Optional[float] = None
    FullAvailableFunds_C: Optional[float] = Field(None, alias='FullAvailableFunds-C')
    FullAvailableFunds_S: Optional[float] = Field(None, alias='FullAvailableFunds-S')
    FullExcessLiquidity: Optional[float] = None
    FullExcessLiquidity_C: Optional[float] = Field(None, alias='FullExcessLiquidity-C')
    FullExcessLiquidity_S: Optional[float] = Field(None, alias='FullExcessLiquidity-S')
    FullInitMarginReq: Optional[float] = None
    FullInitMarginReq_C: Optional[float] = Field(None, alias='FullInitMarginReq-C')
    FullInitMarginReq_S: Optional[float] = Field(None, alias='FullInitMarginReq-S')
    FullMaintMarginReq: Optional[float] = None
    FullMaintMarginReq_C: Optional[float] = Field(None, alias='FullMaintMarginReq-C')
    FullMaintMarginReq_S: Optional[float] = Field(None, alias='FullMaintMarginReq-S')
    GrossPositionValue: Optional[float] = None
    GrossPositionValue_C: Optional[float] = Field(None, alias='GrossPositionValue-C')
    GrossPositionValue_S: Optional[float] = Field(None, alias='GrossPositionValue-S')
    IndianStockHaircut: Optional[float] = None
    IndianStockHaircut_C: Optional[float] = Field(None, alias='IndianStockHaircut-C')
    IndianStockHaircut_S: Optional[float] = Field(None, alias='IndianStockHaircut-S')
    InitMarginReq: Optional[float] = None
    InitMarginReq_C: Optional[float] = Field(None, alias='InitMarginReq-C')
    InitMarginReq_S: Optional[float] = Field(None, alias='InitMarginReq-S')
    InsuredDeposit: Optional[float] = None
    InsuredDeposit_C: Optional[float] = Field(None, alias='InsuredDeposit-C')
    InsuredDeposit_S: Optional[float] = Field(None, alias='InsuredDeposit-S')
    LookAheadAvailableFunds: Optional[float] = None
    LookAheadAvailableFunds_C: Optional[float] = Field(
        None, alias='LookAheadAvailableFunds-C'
    )
    LookAheadAvailableFunds_S: Optional[float] = Field(
        None, alias='LookAheadAvailableFunds-S'
    )
    LookAheadExcessLiquidity: Optional[float] = None
    LookAheadExcessLiquidity_C: Optional[float] = Field(
        None, alias='LookAheadExcessLiquidity-C'
    )
    LookAheadExcessLiquidity_S: Optional[float] = Field(
        None, alias='LookAheadExcessLiquidity-S'
    )
    LookAheadInitMarginReq: Optional[float] = None
    LookAheadInitMarginReq_C: Optional[float] = Field(
        None, alias='LookAheadInitMarginReq-C'
    )
    LookAheadInitMarginReq_S: Optional[float] = Field(
        None, alias='LookAheadInitMarginReq-S'
    )
    LookAheadMaintMarginReq: Optional[float] = None
    LookAheadMaintMarginReq_C: Optional[float] = Field(
        None, alias='LookAheadMaintMarginReq-C'
    )
    LookAheadMaintMarginReq_S: Optional[float] = Field(
        None, alias='LookAheadMaintMarginReq-S'
    )
    MaintMarginReq: Optional[float] = None
    MaintMarginReq_C: Optional[float] = Field(None, alias='MaintMarginReq-C')
    MaintMarginReq_S: Optional[float] = Field(None, alias='MaintMarginReq-S')
    NetLiquidation: Optional[float] = None
    NetLiquidation_C: Optional[float] = Field(None, alias='NetLiquidation-C')
    NetLiquidation_S: Optional[float] = Field(None, alias='NetLiquidation-S')
    NetLiquidationUncertainty: Optional[float] = None
    PASharesValue: Optional[float] = None
    PASharesValue_C: Optional[float] = Field(None, alias='PASharesValue-C')
    PASharesValue_S: Optional[float] = Field(None, alias='PASharesValue-S')
    PostExpirationExcess: Optional[float] = None
    PostExpirationExcess_C: Optional[float] = Field(
        None, alias='PostExpirationExcess-C'
    )
    PostExpirationExcess_S: Optional[float] = Field(
        None, alias='PostExpirationExcess-S'
    )
    PostExpirationMargin: Optional[float] = None
    PostExpirationMargin_C: Optional[float] = Field(
        None, alias='PostExpirationMargin-C'
    )
    PostExpirationMargin_S: Optional[float] = Field(
        None, alias='PostExpirationMargin-S'
    )
    RegTEquity: Optional[float] = None
    RegTEquity_S: Optional[float] = Field(None, alias='RegTEquity-S')
    RegTMargin: Optional[float] = None
    RegTMargin_S: Optional[float] = Field(None, alias='RegTMargin-S')
    SMA: Optional[float] = None
    SMA_S: Optional[float] = Field(None, alias='SMA-S')
    TotalCashValue: Optional[float] = None
    TotalCashValue_C: Optional[float] = Field(None, alias='TotalCashValue-C')
    TotalCashValue_S: Optional[float] = Field(None, alias='TotalCashValue-S')


class AccountsAccountSummaryGetResponse(BaseModel):
    Info_1: Optional[Info] = Field(None, alias='Info')
    Ledger: Optional[List[LedgerItem]] = None
    Summary_1: Optional[Summary] = Field(None, alias='Summary')


class Side6(Enum):
    field_1 = 1
    field_2 = 2


class AccountsAccountTradesGetResponseItem(BaseModel):
    AvgPrice: Optional[float] = None
    Commission: Optional[float] = None
    CommissionCurrency: Optional[str] = None
    ContractId: Optional[float] = None
    Currency: Optional[str] = None
    CustomerOrderId: Optional[float] = None
    ExecId: Optional[str] = None
    ExecutionTime: Optional[str] = None
    FilledQuantity: Optional[float] = None
    LastMarket: Optional[str] = None
    ListingExchange: Optional[str] = None
    OrderId: Optional[str] = None
    OrderType_1: Optional[OrderType] = Field(None, alias='OrderType')
    Quantity: Optional[float] = None
    RemainingQuantity: Optional[float] = None
    Side: Optional[Side6] = None
    Ticker: Optional[str] = None
    TradePrice: Optional[float] = None
    TradeSize: Optional[float] = None


class AccountsAccountTradesGetResponse(
    RootModel[List[AccountsAccountTradesGetResponseItem]]
):
    root: List[AccountsAccountTradesGetResponseItem]


class MappingItem(BaseModel):
    bit: Optional[float] = None
    code: Optional[str] = None
    exchange: Optional[str] = None


class MarketdataExchangeComponentsGetResponseItem(BaseModel):
    Complete: Optional[bool] = None
    ConId: Optional[float] = None
    mapping: Optional[List[MappingItem]] = None


class MarketdataExchangeComponentsGetResponse(
    RootModel[List[MarketdataExchangeComponentsGetResponseItem]]
):
    root: List[MarketdataExchangeComponentsGetResponseItem]


class MarketdataSnapshotGetRequestItem(BaseModel):
    conid: Optional[float] = Field(
        None,
        description='The internal IB identifier for the trading product specified as an integer.',
    )
    currency: Optional[str] = Field(
        None, description='The currency in which the given pair trades.'
    )
    exchange: Optional[str] = Field(
        None,
        description='The exchange on which the trading product is listed (required for type=STK).',
    )
    symbol: Optional[str] = Field(
        None, description='The symbol that identifies the trading product.'
    )
    type: Optional[str] = Field(
        None, description='The instrument type of the contract (CASH).'
    )


class MarketdataSnapshotGetRequest(RootModel[List[MarketdataSnapshotGetRequestItem]]):
    root: List[MarketdataSnapshotGetRequestItem]


class Bid(BaseModel):
    market: Optional[float] = None
    price: Optional[float] = None
    size: Optional[float] = None


class Closing(BaseModel):
    price: Optional[float] = None


class Offer(BaseModel):
    market: Optional[float] = None
    price: Optional[float] = None
    size: Optional[float] = None


class Temporality(Enum):
    number_0 = 0
    number_1 = 1


class Trade(BaseModel):
    market: Optional[float] = None
    price: Optional[float] = None
    size: Optional[float] = None
    time: Optional[float] = None


class MarketdataSnapshotGetResponseItem(BaseModel):
    Bid_1: Optional[Bid] = Field(None, alias='Bid')
    Closing_1: Optional[Closing] = Field(None, alias='Closing')
    Complete: Optional[bool] = None
    Conid: Optional[str] = None
    Offer_1: Optional[Offer] = Field(None, alias='Offer')
    Temporality_1: Optional[Temporality] = Field(
        None, alias='Temporality', description='0 = Real time data\n1 = Delayed data\n'
    )
    Trade_1: Optional[Trade] = Field(None, alias='Trade')


class MarketdataSnapshotGetResponse(RootModel[List[MarketdataSnapshotGetResponseItem]]):
    root: List[MarketdataSnapshotGetResponseItem]


class OauthAccessTokenPostRequest(BaseModel):
    oauth_consumer_key: Optional[str] = Field(
        None,
        description='The 25-character hexadecimal string that was obtained from Interactive Brokers during the OAuth consumer registration process.',
    )
    oauth_nonce: Optional[str] = Field(
        None, description='A random string uniquely generated for each request.'
    )
    oauth_signature: Optional[str] = Field(
        None,
        description='The signature for the request generated using the method specified in the oauth_signature_method parameter. See section 9 of the OAuth v1.0a specification for more details on signing requests.',
    )
    oauth_signature_method: Optional[str] = Field(
        None,
        description="The signature method used to sign the request. Currently only 'RSA-SHA256' is supported.",
    )
    oauth_timestamp: Optional[str] = Field(
        None,
        description='Timestamp expressed in seconds since 1/1/1970 00:00:00 GMT. Must be a positive integer and greater than or equal to any timestamp used in previous requests.',
    )
    oauth_token: Optional[str] = Field(
        None, description='The request token obtained from IB via /request_token.'
    )
    oauth_verifier: Optional[str] = Field(
        None,
        description='The verification code received from IB after the user has granted authorization.',
    )


class OauthAccessTokenPostResponse(BaseModel):
    oauth_token: Optional[str] = None
    oauth_token_secret: Optional[str] = None


class OauthLiveSessionTokenPostRequest(BaseModel):
    diffie_hellman_challenge: Optional[str] = Field(
        None,
        description='Challenge value calculated using the Diffie-Hellman prime and generated provided during the registration process. See the "OAuth at Interactive Brokers" document for more details. \n',
    )
    oauth_consumer_key: Optional[str] = Field(
        None,
        description='The 25-character hexadecimal string that was obtained from Interactive Brokers during the OAuth consumer registration process.',
    )
    oauth_nonce: Optional[str] = Field(
        None, description='A random string uniquely generated for each request.'
    )
    oauth_signature: Optional[str] = Field(
        None,
        description='The signature for the request generated using the method specified in the oauth_signature_method parameter. See section 9 of the OAuth v1.0a specification for more details on signing requests.',
    )
    oauth_signature_method: Optional[str] = Field(
        None,
        description="The signature method used to sign the request. Currently only 'RSA-SHA256' is supported.",
    )
    oauth_timestamp: Optional[str] = Field(
        None,
        description='Timestamp expressed in seconds since 1/1/1970 00:00:00 GMT. Must be a positive integer and greater than or equal to any timestamp used in previous requests.',
    )
    oauth_token: Optional[str] = Field(
        None, description='The request token obtained from IB via /request_token.'
    )


class OauthLiveSessionTokenPostResponse(BaseModel):
    diffie_hellman_response: Optional[str] = None
    live_session_token_signature: Optional[str] = None


class OauthRequestTokenPostRequest(BaseModel):
    oauth_callback: Optional[str] = Field(
        None,
        description="An absolute URL to which IB will redirect the user. This URL is provided by the consumer during registration. This parameter must be set to 'oob'.  ",
    )
    oauth_consumer_key: Optional[str] = Field(
        None,
        description='The 25-character hexadecimal string that was obtained from Interactive Brokers during the OAuth consumer registration process.',
    )
    oauth_nonce: Optional[str] = Field(
        None, description='A random string uniquely generated for each request.'
    )
    oauth_signature: Optional[str] = Field(
        None,
        description='The signature for the request generated using the method specified in the oauth_signature_method parameter. See section 9 of the OAuth v1.0a specification for more details on signing requests.',
    )
    oauth_signature_method: Optional[str] = Field(
        None,
        description="The signature method used to sign the request. Currently only 'RSA-SHA256' is supported.",
    )
    oauth_timestamp: Optional[str] = Field(
        None,
        description='Timestamp expressed in seconds since 1/1/1970 00:00:00 GMT. Must be a positive integer and greater than or equal to any timestamp used in previous requests.',
    )


class OauthRequestTokenPostResponse(BaseModel):
    oauth_token: Optional[str] = None


class SecdefGetRequest(BaseModel):
    conid: Optional[float] = Field(
        None,
        description='The internal IB identifier for the trading product specified as an integer.',
    )
    currency: Optional[str] = Field(
        None, description='The currency in which the given pair trades.'
    )
    exchange: Optional[str] = Field(
        None,
        description='The exchange on which the trading product is listed (required for type=STK).',
    )
    symbol: Optional[str] = Field(
        None, description='The symbol that identifies the trading product.'
    )
    type: Optional[str] = Field(
        None, description='The instrument type of the contract (CASH).'
    )


class SecdefGetResponseItem(BaseModel):
    CompanyName: Optional[str] = None
    ContractId: Optional[float] = None
    Currency: Optional[str] = None
    Exchange: Optional[str] = None
    SecurityType: Optional[str] = None
    Ticker: Optional[str] = None


class SecdefGetResponse(RootModel[List[SecdefGetResponseItem]]):
    root: List[SecdefGetResponseItem]


class OrderState(BaseModel):
    ContractId: Optional[float] = None
    CustomerOrderId: Optional[float] = None
    FilledQuantity: Optional[float] = None
    ListingExchange: Optional[str] = None
    OrderType_1: Optional[OrderType] = Field(None, alias='OrderType')
    OutsideRTH: Optional[str] = None
    Price: Optional[float] = None
    RemainingQuantity: Optional[float] = None
    Side_1: Optional[Side] = Field(None, alias='Side')
    Status: Optional[OrderStatus] = None
    Ticker: Optional[str] = None
    TimeInForce_1: Optional[TimeInForce] = Field(None, alias='TimeInForce')
    TransactionTime: Optional[str] = None
    Warning: Optional[str] = None


class AccountsAccountOrdersGetResponse(RootModel[List[OrderState]]):
    root: List[OrderState]


class AccountsAccountOrdersPostResponse(RootModel[List[OrderState]]):
    root: List[OrderState]


class AccountsAccountOrdersCustomerOrderIdGetResponse(RootModel[List[OrderState]]):
    root: List[OrderState]
